### ISSUE TITLE
Evaluate() error

### ISSUE THREAD

**Issue by BhideSoumitra** [MesserLab/ResourceExplicitModels#1]
While running inelastic_resource_explicit_repro_square.slim, "nearestInteractingNeighbors" on line 52 causes an error as follows:
"the interaction must be evaluated for the receiver and exerter subpopulations, by calling evaluate(), before any queries" thus causes simulation to fail.

**Comment by samchamper** [comment]
Hi Soumitra,

The script runs fine on my end. Mind letting me know what environment and what version of SLiM you're running in? Or if you've made alterations to the model, and want to chat about it, feel free to shoot me an email at sc2224    -at-    cornell,edu.

**Comment by BhideSoumitra** [comment]
I am running SLiM 4.0.1 on Windows. I have not made any alterations to the model.

**Comment by samchamper** [comment]
Okay, that's the issue then. I neglected to mention it anywhere in this repo (the paper is almost ready, by the way!), but these models have been developed using the current GitHub head for SLiM (https://github.com/MesserLab/SLiM). If you use the latest official release (4.0.1 as of writing this), these models have two issues: the "resource-explicit reproduction" models don't work (I had actually forgotten that this was the case - sorry you ran into this issue!), and the runtime of the inelastic models at population sizes over 4 million is much slower than it should be. Both of these issues are fixed in the GitHub head for SLiM (and of course these issues won't be present in the next official release of SLiM).

If you switch over to the latest version and have any additional issues, let me know!
